### ISSUE TITLE
can't run testcurses.py

### ISSUE THREAD

**Issue by gtozzi** [qpython-android/qpython.org#121]
/data/data/com.hipipal.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/com.hipipal.qpyplus/scripts3/testcurses.py" && exit
pyplus/scripts3/testcurses.py" && exit   <
Traceback (most recent call last):
  File "/storage/emulated/0/com.hipipal.qpyplus/scripts3/testcurses.py", line 6, in <module>
    win=curses.initscr()
  File "/data/data/com.hipipal.qpy3/files/lib/python3.2/python32.zip/curses/__init__.py", line 31, in initscr
_curses.error: setupterm: could not find terminal
1|u0_a464@m7:/ $

**Comment by gtozzi** [comment]
This app is great, thank you!

**Comment by riverfor** [comment]
Can you insert "#qpy:kivy" which will let it run with kivy,  then retry ?

**Comment by gtozzi** [comment]
I've inserted it at the beginning of the script, but nothing changes.
