### ISSUE TITLE
test.py gdata test is failing

### ISSUE THREAD

**Issue by tempseptember** [qpython-android/qpython.org#144]
While running test.py
It fails in gdata tests.
The console log is....

/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/org.qpython.qpy/scripts3/test.py" && exit
qpython.qpy/scripts3/test.py" && exit   <
Running test_phone_state...  PASS
Running test_notify...  PASS
Running test_sensors...  PASS
Running test_alert_dialog_with_list...  PASS
Running test_alert_dialog_with_single_choice_list...  PASS
Running test_wifi...  PASS
Running test_ringer_silent...  PASS
Running test_gps...  PASS
Running test_alert_dialog_with_buttons...  PASS
Running test_imports...  PASS
Running test_horizontal_progress...  PASS
Running test_vibrate...  PASS
Running test_speak...  PASS
Running test_geocode...  PASS
Running test_clipboard...  PASS
Running test_make_toast...  PASS
Running test_alert_dialog_with_multi_choice_list...  PASS
Running test_get_last_known_location...  PASS
Running test_alert_dialog...  PASS
Running test_spinner_progress...  PASS
Running test_battery...  PASS
Running test_ringer_volume...  PASS
Running test_get_running_packages...  PASS
Running test_gdata... Traceback (most recent call last):
  File "/storage/emulated/0/org.qpython.qpy/scripts3/test.py", line 232, in <module>
    if value():
  File "/storage/emulated/0/org.qpython.qpy/scripts3/test.py", line 58, in test_gdata
    documents_feed = client.GetDocumentListFeed()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/gdata/docs/service.py", line 260, in GetDocumentListFeed
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/gdata/docs/service.py", line 239, in QueryDocumentListFeed
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/python32.zip/gdata/service.py", line 1108, in Get
gdata.service.RequestError: {'status': 401, 'body': b'<HTML>\n<HEAD>\n<TITLE>Authorization required</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Authorization required</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n', 'reason': 'Authorization required'}
1|u0_a164@osprey_ud2:/ $

**Comment by tempseptember** [comment]
System is running Android v6.0.1
