### ISSUE TITLE
jnius module crash on import

### ISSUE THREAD

**Issue by oceanpix** [qpython-android/qpython.org#152]
Hi! I cannot use of the jnius module in QPython. It crash with a system error as soon as it's imported.
Similarly the plyer module output jnius errors when its definitions are called (plyer.vibrator)

/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh && exit
y/files/bin/qpython-android5.sh && exit  <
Python 2.7.2 (default, Nov  2 2015, 01:07:37)
[GCC 4.9 20140827 (prerelease)] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import jnius
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/__init__.py", line 13, in <module>
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/site-packages/jnius/reflect.py", line 9, in <module>
  File "jnius_export_class.pxi", line 44, in jnius.jnius.MetaJavaClass.__new__ (jnius/jnius.c:13255)
SystemError: NULL result without error in PyObject_Call
>>>

**Comment by riverfor** [comment]
insert "#qpy:kivy" into your script to let it run with kivy.
