### ISSUE TITLE
installing kivy on qpython3 

### ISSUE THREAD

**Issue by prxy15** [qpython-android/qpython.org#174]
hi, i have this issue when i try to install kivy 
same thing with ver 1.10 and 1.9.x can anyone help me ? 
------------------------------------------------------------
/data/user/0/org.qpython.qpy3/files/bin/pip run on Thu Sep  7 05:52:56 2017
Downloading/unpacking kivy==1.9.1

  Running setup.py egg_info for package kivy

    Using distutils

    

    Detected Cython version 0.25.2

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/storage/emulated/0/qpython/cache/pip-build/kivy/setup.py", line 353, in <module>

        import kivy

      File "kivy/__init__.py", line 37, in <module>

        from kivy.compat import PY2

      File "kivy/compat.py", line 72, in <module>

        clock = time.perf_counter

    AttributeError: 'module' object has no attribute 'perf_counter'

    Complete output from command python setup.py egg_info:

    Using distutils

Detected Cython version 0.25.2

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/kivy/setup.py", line 353, in <module>

    import kivy

  File "kivy/__init__.py", line 37, in <module>

    from kivy.compat import PY2

  File "kivy/compat.py", line 72, in <module>

    clock = time.perf_counter

AttributeError: 'module' object has no attribute 'perf_counter'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/kivy

Exception information:
Traceback (most recent call last):
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/basecommand.py", line 107, in main
    status = self.run(options, args)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/commands/install.py", line 256, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 1042, in prepare_files
    req_to_install.run_egg_info()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/pip-1.2.1-py3.2.egg/pip/util.py", line 612, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/kivy

**Comment by riverfor** [comment]
qpython3 does not support kivy yet.

**Comment by prxy15** [comment]
oh! thanks for answer, i will try with ver 2

**Comment by caffeinatedMike** [comment]
It's been 3 1/2 years. Is this still the case? I just tried using `#qpy:kivy` in QPython 3L and received the notification that it still isn't supported on python 3. I'm very surprised by this since python 2 has officially been sunset.

I was really hoping to be able to utilize Kivy 2.0 with QPython 3L in order to test my app directly on my device.
