### ISSUE TITLE
Can not install PIL or Pillow Library on Qpython

### ISSUE THREAD

**Issue by Python88** [qpython-android/qpython.org#198]
Can not install PIL or Pillow Library on Qpython

Please Help.
![screenshot_2019-02-02-19-31-43-876_org qpython qpy](https://user-images.githubusercontent.com/17029805/52165132-aad57d00-2722-11e9-98fc-c7e2d975e4b3.png)

/data/user/0/org.qpython.qpy/files/bin/qpython-android5.sh "/data/user/0/org.qpython.qpy/files/bin/qpypi.py" && exit
org.qpython.qpy/files/bin/qpypi.py" && exit <
Input pip commands, ie: pip install {module} OR pip help
-->pip install Pillow
Collecting Pillow
  Using cached https://files.pythonhosted.org/packages/3c/7e/443be24431324bd34d22dd9d11cc845d995bcd3b500676bcf23142756975/Pillow-5.4.1.tar.gz
Installing collected packages: Pillow
  Running setup.py install for Pillow ... error
    Complete output from command /data/user/0/org.qpython.qpy/files/bin/python-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-vjA1bC/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-nfzVhn-record/install-record.txt --single-version-externally-managed --compile:
    Exception installing mp_compile, proceeding without:[Errno 38] Function not implemented
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv8l-2.7
    creating build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/features.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/OleFileIO.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv8l-2.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build-vjA1bC/Pillow/setup.py", line 812, in <module>
        raise RequiredDependencyException(msg)    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
**Command "/data/user/0/org.qpython.qpy/files/bin/python-android5 -u -c "import setuptools, tokenize;__file__='/storage/emulated/0/qpython/cache/pip-build-vjA1bC/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /storage/emulated/0/qpython/cache/pip-nfzVhn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build-vjA1bC/Pillow/**
-->

**Comment by Python88** [comment]
When using pip install Pillow

I get this every time..

![screenshot_2019-02-02-19-43-54-995_org qpython qpy](https://user-images.githubusercontent.com/17029805/52165155-fab44400-2722-11e9-8f85-04e313fa174f.png)

**Comment by BruceLee569** [comment]
+1

**Comment by hyankov** [comment]
Same here

**Comment by xiaochuan8264** [comment]
guess the problem is still unsolved

**Comment by EEEureka** [comment]
Some libraries are based on c/c++, which  need more compiler. I don't know when they will solve it, because it's really a little hard for developers.
