### ISSUE TITLE
Latest Version 3.3.2 is broken.

### ISSUE THREAD

**Issue by jayunger** [qpython-android/qpython.org#220]
Auto upgrade from 2.9.9 caused serious flaws on Android 10,  QPython QSL4A cannot continue running if QPython is closed, has to be restarted every time a new script execution is attempted. Also home screen links to scripts are incorrectly created causing QPython to open without executing the referenced script, however old shortcuts created prior to auto upgrade continue to work properly and execute the reference script.

Also, please make auto upgrade optional so defective releases can be skipped until bugs are corrected.

**Comment by jayunger** [comment]
Below is error log from exception thrown when trying to restart QPython after crash

BOARD=msm8998
CPU_ABI2=
HOST=SWDH4621
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@3e647e3
CPU_ABI=arm64-v8a
PERMISSIONS_REVIEW_REQUIRED=true
DISPLAY=QP1A.190711.020.T830XXU5CVG2
SUPPORTED_ABIS=[Ljava.lang.String;@f85f5e0
FINGERPRINT=samsung/gts4lwifixx/gts4lwifi:10/QP1A.190711.020/T830XXU5CVG2:user/release-keys
PRODUCT=gts4lwifixx
ID=QP1A.190711.020
TYPE=user
SERIAL=unknown
DEVICE=gts4lwifi
MODEL=SM-T830
MANUFACTURER=samsung
USER=dpi
BRAND=samsung
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@75a6412
HARDWARE=qcom
IS_DEBUGGABLE=false
BOOTLOADER=T830XXU5CVG2
RADIO=unknown
UNKNOWN=unknown
IS_EMULATOR=false
TAGS=release-keys
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.qpython.qpy/org.qpython.qpy.main.activity.AppListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.qpython.qpy.console.ScriptExec.playScript(android.content.Context, java.lang.String, java.lang.String)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.qpython.qpy.console.ScriptExec.playScript(android.content.Context, java.lang.String, java.lang.String)' on a null object reference
	at org.qpython.qpy.console.ScriptExec.play(ScriptExec.java:85)
	at org.qpython.qpy.main.activity.AppListActivity.runShortcut(AppListActivity.java:131)
	at org.qpython.qpy.main.activity.AppListActivity.onCreate(AppListActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:7957)
	at android.app.Activity.performCreate(Activity.java:7946)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
	... 11 more
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.qpython.qpy.console.ScriptExec.playScript(android.content.Context, java.lang.String, java.lang.String)' on a null object reference
	at org.qpython.qpy.console.ScriptExec.play(ScriptExec.java:85)
	at org.qpython.qpy.main.activity.AppListActivity.runShortcut(AppListActivity.java:131)
	at org.qpython.qpy.main.activity.AppListActivity.onCreate(AppListActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:7957)
	at android.app.Activity.performCreate(Activity.java:7946)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
