### ISSUE TITLE
plyer.camera.take_picture() is not working

### ISSUE THREAD

**Issue by funs** [qpython-android/qpython.org#41]
Anyone success in plyer.camera under qpython?
My code:
*************
def dotakepic(self):
      d='/storage/emulated/0/com.hipipal.qpyplus/projects/plyertest/example.jpg'
        camera.take_picture(filename=d, on_complete=self.done)
        
    def done(self，d): 
        self.ids.lblCam.text = d

**********
Errors:
Traceback (most recent call last):
   File ".last_tmp.py", line 43, in <module>
     CamApp().run() 
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/app.py", line 792, in run
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 481, in runTouchApp
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 381, in mainloop
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 287, in _mainloop
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 324, in idle
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 309, in dispatch_input
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 220, in post_dispatch_input
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4409)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 648, in on_motion
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4409)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 660, in on_touch_down
   File "_event.pyx", line 316, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4409)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/uix/widget.py", line 284, in on_touch_down
   File "_event.pyx", line 312, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:4359)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/kivy/lang.py", line 1299, in custom_callback
   File "./cam.kv", line 5, in <module>
     on_touch_down:root.dotakepic()
   File ".last_tmp.py", line 23, in dotakepic
     camera.take_picture(filename=d, on_complete=self.done())
   File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/plyer-1.2.1-py2.7.egg/plyer/facades.py", line 70, in take_picture
     self._take_picture(filename=filename, on_complete=on_complete)
   File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/plyer-1.2.1-py2.7.egg/plyer/platforms/android/camera.py", line 21, in _take_picture
     android.activity.bind(on_activity_result=self._on_activity_result)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/android/activity.py", line 60, in bind
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/android/activity.py", line 35, in __init__
   File "jnius_proxy.pxi", line 31, in jnius.jnius.PythonJavaClass.__init__ (jnius/jnius.c:21667)
   File "jnius_proxy.pxi", line 160, in jnius.jnius.create_proxy_instance (jnius/jnius.c:23587)
   File "/QPython/core/build/python-install/lib/python2.7/site-packages/jnius/reflect.py", line 150, in autoclass
   File "jnius_export_func.pxi", line 23, in jnius.jnius.find_javaclass (jnius/jnius.c:11773)
 jnius.jnius.JavaException: Class not found 'org/jnius/NativeInvocationHandler'

**Comment by riverfor** [comment]
It seems like the plyer's bug.

Can you paste related code or complete output with http://gist.github.com/ ? So I can try the script in my \ device.

Thanks.
