### ISSUE TITLE
Unable to run kivy with qpython1.2.1

### ISSUE THREAD

**Issue by Reins981** [qpython-android/qpython.org#92]
Kivy1.8.0 has a problem to find some modules needed. Here is the log output:
INFO:kivy:Kivy v1.8.0
ERROR:kivy:Error when copying logo directory
Traceback (most recent call last):
  File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/kivy-1.8.0-py2.7.egg/kivy/__init__.py", line 272, in <module>
    shutil.copytree(join(kivy_data_dir, 'logo'), icon_dir)
  File "/QPython/QPython2-core/build/python-install/lib/python2.7/shutil.py", line 168, in copytree
OSError: [Errno 2] No such file or directory: '/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/kivy-1.8.0-py2.7.egg/kivy/data/logo'
WARNING:kivy:stderr: Traceback (most recent call last):
WARNING:kivy:stderr:   File ".last_tmp.py", line 8, in <module>
WARNING:kivy:stderr:     from kivy.app import App
WARNING:kivy:stderr:   File "/data/data/com.hipipal.qpyplus/files/lib/python2.7/site-packages/kivy-1.8.0-py2.7.egg/kivy/__init__.py", line 378, in <module>
WARNING:kivy:stderr:     from kivy.modules import Modules
WARNING:kivy:stderr: ImportError: No module named modules
INFO:kivy:Kivy v1.8.0

**Comment by joadavis** [comment]
I've been having trouble getting old scripts to run for months.  Old projects I created that worked fine in old versions of QPython that relied on Kivy (think it was using 1.7.2) fail in ugly ways, even when I try to add the various new comment decorators at the top of the script.  It appears that 1.2.2 is providing Kivy 1.9 now, and even with the #qpy:2 and #qpy:kivy headers it fails with some error about unable to open the Window.

Even just opening a new file in editor and hitting the Snippet for QPy_KivyApp will produce code that gets the logo error mentioned above by Reins981.

Really frustrating that backward compatibility is not included in updates!  Or a quick way to bring your old script up to date! That should be easy!

**Comment by Reins981** [comment]
Yes you are right Joadavis. It seems to be that some kivy module helper classes have changed significantly. They only way is to hack these module classes for your own needs
