### ISSUE TITLE
Non recoverable failure in name resolution

### ISSUE THREAD

**Issue by aleskandro** [qpython-android/qpython.org#99]
Just installed Qpython3 on my Zopo zp980+ Android 4.4.2.
I can't run any script that use sl4a because of this:
```            
Traceback (most recent call last):
  File "/storage/sdcard0/com.hipipal.qpyplus/scripts3/hello_world.py", line 2, in <module>
    droid = sl4a.Android()
  File "/data/data/com.hipipal.qpy3/files/lib/python3.2/python32.zip/sl4a.py", line 34, in __init__
  File "/data/data/com.hipipal.qpy3/files/lib/python3.2/python32.zip/socket.py", line 386, in create_connection
socket.gaierror: [Errno 4] non-recoverable failure in name resolution.
```
Help please, I was excited from this app, I would write my script!

**Comment by devDesu** [comment]
I have that issue too.
Android 5.1 Lenovo K3-Note
Both Qpython and Qpython3 gives me socket.gaierror

**Comment by riverfor** [comment]
Is it OK after restarting the SL4A service (from setting apartment) ?

**Comment by devDesu** [comment]
Looks like I'm not able to stop sl4a in QPython. It just toasts me success
and keeps showing 'running' in the status area. And in QPython3 it gives me
socket.py error in both cases(sl4a turned off and turned on)

чт, 17 дек. 2015, 9:33, River <notifications@github.com>:
